# Generated by Django 4.2.6 on 2023-10-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_testcase_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
